import type { Metadata } from "next";

import { Raleway, Noto_Serif } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import "./globals.scss";
import { SiteProvider } from "@/context/SiteContext";

const raleway = Raleway({
  subsets: ["cyrillic"],
  weight: ["400"],
  variable: "--font-raleway",
});
const notoSerif = Noto_Serif({
  subsets: ["cyrillic"],
  weight: ["300"],
  variable: "--font-notoSerif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={`${raleway.variable} ${notoSerif.variable}`}>
        <SiteProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </SiteProvider>
      </body>
    </html>
  );
}
